### ISSUE TITLE
Error on fresh install: `TypeError: type NoneType doesn't define __round__ method`

### ISSUE THREAD

**Issue by IgnisDa** [chunned/databass#9]
Hi, I am the author of Ryot. You [mentioned](https://github.com/IgnisDa/ryot/issues/49#issuecomment-2116423099) this project in the issue tracker for Music tracking. I tried to run the application using the instructions but it does not work.

Here is the error:

![image](https://github.com/chunned/databass/assets/60938164/1fc1e25d-2e57-4641-83f1-7f0bdc13dba7)

**Comment by chunned** [comment]
Hi, thanks for checking out my project! 

This should now be fixed - I had forgotten to add some checks for when the database is empty. 

I see you did so already in your screenshot, but I also updated the deployment instructions to mention that you need to `touch music.db` prior to launching the Docker compose, otherwise it'll attempt to mount as a directory. 

Let me know if you run into any other issues - this is my first real project, and I'm not a developer by trade, so I'm sure there will be some more things like this that I've forgotten about.

**Comment by IgnisDa** [comment]
[diff.txt](https://github.com/user-attachments/files/15934760/diff.txt)

I had to make all these changes to your project to get it running locally.

**Comment by chunned** [comment]
Thank you very much for spotting these! 

I fixed the two stats errors earlier in [this commit](https://github.com/chunned/databass/commit/6856a47b77b18d8a09e3b5023f4d4e237b07e35c) - reopening this so I don't forget to add the other fixes tomorrow
